### ISSUE TITLE
Crash that I ran into repeatedly during Monday's test

### ISSUE THREAD

**Issue by taymonbeal** [gwillen/solstice-audio-test#103]
https://sentry.io/share/issue/ee0423583f3a45d2aba0032e120389b0/

We suspected that this might have been Windows-specific. @gwillen, did you manage to repro it?

**Comment by gwillen** [comment]
Oh, I thought you repeatedly ran into a different crash? I thought you had said you repeatedly ran into the crash that mentions "placeholderchunk".

This crash was not windows-specific at all, it was just "my refactor broke clicking lyrics" and I fixed it. (I'd have to check if the fix is pushed, but it was a simple fix.)

I thought there was some problem that hit you as soon as you calibrated, before clicking anything? (Or was that when this one hit you?)

Glenn

**Comment by taymonbeal** [comment]
No, this one happened shortly after the start of the backing track. You're saying it's fixed?

**Comment by gwillen** [comment]
I don't know, because literally the only call to this function is on BucketSinging.js line 291, which only gets run if you are lyriclead and you clicked a lyric. I don't know how it could possibly happen at any other time.

But the specific crash on line 761 of app.js _is_ fixed, I just have no idea how you could possibly have executed that code.

Glenn

**Comment by taymonbeal** [comment]
I did click lyrics.

**Comment by gwillen** [comment]
Then yeah, it's fixed.

(It reoccured this evening because it turns out I had fixed it on gwillen-dev but not on master. It is now on master.)
