### ISSUE TITLE
People are randomly muted

### ISSUE THREAD

**Issue by graceavery** [gwillen/solstice-audio-test#148]
Over the course of 3 hours I was muted twice without having pressed the mute button.  Other people were muted as well.  (evening of Dec 24)

**Comment by jeffkaufman** [comment]
Thanks! This happens when the system detects that you're running behind because of either CPU or network issues, and you would be causing a problem for the person after you. The interface is currently pretty bad: randomly and inexplicably muting people is much worse than saying "you've been muted due to lag" and offering a button to try again.

I have a better UI for this coming in #146.

@gwillen looks like even with your improved catching up code this is still triggering

**Comment by jeffkaufman** [comment]
The better user interface for this is now live
