### ISSUE TITLE
Bucket Brigade questions

### ISSUE THREAD

**Issue by jasaco** [gwillen/solstice-audio-test#179]
I'm logged in but no one's here, not even Jeff... :(

**Comment by jeffkaufman** [comment]
That's strange, we didn't see you.  Were you at https://echo.jefftk.com?

**Comment by jasaco** [comment]
No. I was at https://www.jefftk.com/echo/

**Comment by jeffkaufman** [comment]
Oh, that explains it.  https://www.jefftk.com/echo is the beta instance of Bucket Brigade, and is completely independent from the main instance at https://echo.jefftk.com.

I'm sorry you missed the demo! If you'd like, I could let you know when I do another one?

**Comment by jasaco** [comment]
Yes, please do! In the meantime, could I ask you a few questions? I played
around on the beta site today and have some questions, if you don't
mind...?

**Comment by jeffkaufman** [comment]
Sure, happy to answer questions!

**Comment by jasaco** [comment]
Thank you, Jeff. I tried the beta site with one other singer today. Some of
my questions might be answered and obvious on the main site and, if so, I
apologize for taking up your time with them.

1. Is there just one "room" where all your clients go (and that's why one
needs to reserve it in advance?) or are there multiple rooms/work-spaces.

2. What's max # of singers who can participate? It looked like there were
just 6 columns? Does that mean max=6?

3. As song leader, I could not hear the other person singing but they heard
me, and the recording was in sync. Should I have been able to hear her too?

4. When there are multiple singers involved, can they all hear each other
simultaneously, or will each one only hear me and then we need to play back
the recording to hear everyone together?

5. The recording had my voice quite loud but hers quite soft. Is there any
way to adjust the mix after recording?

6. Can the recording be downloaded? If so, only as one unit, or as separate
voices that can later be mixed in post-production?

7. I see there are 2 latencies reported: Client and "True". Which is more
important to observe and what is a good (low) latency level?

8. How to upload a backing track? (Might be obvious on the main site?)

9. Finally, for a band, let's say, whose members both play an instrument
and sing, can this system still work? Would one need to premix the
instrument+vox signals before feeding it into the Bucket Brigade?

Sorry to barrage you with so many questions but obviously I'm a newbie (and
very sorry to have missed the demo). Please do let me know when you
schedule the next one. And a huge THANK YOU to you for even doing this and
making it so readily available to all!

Best wishes,
Jim

**Comment by jeffkaufman** [comment]
> 1. Is there just one "room" where all your clients go (and that's why one
needs to reserve it in advance?) or are there multiple rooms/work-spaces.

Yes, there is just one room.

(Well, technically, there is a second room on the better instance, as you accidentally discovered, but I use that one for developing the software and you shouldn't rely on it)

> 2. What's max # of singers who can participate?

I currently have it set to allow in 35 people. I haven't tested it with that many, but it should work with up to about 50?

The underlying singing software, aside from the video call portion, can support much larger numbers. We ran a solstice celebration with a little over 200 people singing together, and on a powerful machine it seems to be able to handle about 1,000.

> It looked like there were just 6 columns?

Each column is a bucket, and you can hear the people in earlier buckets and be heard by the people in later buckets. You can have multiple people in the same bucket, though, so you're not limited to just six people.

> 3. As song leader, I could not hear the other person singing but they heard me, and the recording was in sync. Should I have been able to hear her too?

No, you can only hear people in buckets before you.  This means that the leader doesn't have as much fun, since they don't get to hear anyone else, but if everyone takes turns leading it's not too bad.

The exception to this is when singing in rounds mode, but that is another complicated topic ;)

> 4. When there are multiple singers involved, can they all hear each other simultaneously, or will each one only hear me and then we need to play back the recording to hear everyone together?

The multiple singers will be automatically assigned different buckets (though you can choose to move between buckets) and each would be able to hear the people in earlier buckets.

> 5. The recording had my voice quite loud but hers quite soft. Is there any way to adjust the mix after recording?

It is possible to change the mix while things are running, but not afterwards. The recordings are mixed down to a single channel.  That the bug settings tab has a rudimentary mixing consul, but be advised that the controls are very sensitive. Typically I'm just turning people from "1" to "1.1" or "0.9", and setting someone to a volume of "2" is very painful.

> 6. Can the recording be downloaded? If so, only as one unit, or as separate voices that can later be mixed in post-production?

In the upper right there is a link "recent recordings", which offers links to download the 20 most recent recordings.

They are already fully mixed down, so it isn't possible to remix.

If that was something you were interested in, however, it would be possible to save each track in full.  I would probably need to get a server with more disk space, though, especially if you had larger groups.

> 7. I see there are 2 latencies reported: Client and "True". Which is more important to observe and what is a good (low) latency level?

Neither matters very much, except as a tool for debugging if things are going wrong.  The system does not rely on having low latency, it just needs consistent latency.

> 8. How to upload a backing track? (Might be obvious on the main site?)

Currently the only way to upload a backing track is to send it to me and I can upload it. Sorry!

> 9. Finally, for a band, let's say, whose members both play an instrument and sing, can this system still work? Would one need to premix the instrument+vox signals before feeding it into the Bucket Brigade?

My experience is that if each person either plays an instrument or sings it does pretty well.  On the other hand, if one person is both playing an instrument and singing, the audio encoder prioritizes the singing and the instrument doesn't sound great.

You would need to mix the instrument and vocal signals, either in the air, by just using one microphone, or with mixer.
