### ISSUE TITLE
Add password support

### ISSUE THREAD

**Issue by jeffkaufman** [gwillen/solstice-audio-test#192]
We could add a field to the reserve tab that takes a password, and hashes it. Then it could tell you to add the hashed string to your calendar event.

If someone visits while a calendar event with a password is active, we prompt them for the password, hash it, and check whether it matches the one on the event.

**Comment by jeffkaufman** [comment]
At least for now this will be implemented entirely client side, and there won't be any attempt to keep out actually determined folks

**Comment by Raemon** [comment]
I think the actual solution here is to fork out different instances as a
central feature in the first place. You'll need to do it eventually (or,
someone will, if BucketBrigade is to hit serious scale). I'm not sure if
there are any local steps towards that that are commensurately easy as
adding the password-prompt and continuing to use the google calendar.

But, my naive expectation if I were to show up at the website is that
rather than dropping directly into a shared musical space, I click "create
event", and that creates a specific url with a long hash-id and a
human-readable slug, and then I send that url to my friends, that's the
core loop of the app (similar to any other videoconferencing app).

**Comment by Raemon** [comment]
(in the limit, I'd assume a commercialized/scalable version of BucketBrigade would probably have a free tier that uses autoscaling+loadbalancing, and takes a bit of a loss on the server cost, and a paid tier that spins up a new server)

**Comment by jeffkaufman** [comment]
If someone else wants to fully scale BB, that's fine with me, but currently I just want to make better use of the single shared instance we have.

Adding password support like this should be reasonably quick

**Comment by Raemon** [comment]
Okay that was indeed quite fast. :P
