### ISSUE TITLE
TypeError: Cannot read property 'interval' of null

### ISSUE THREAD

**Issue by taymonbeal** [gwillen/solstice-audio-test#21]
```
TypeError: Cannot read property 'interval' of null
TypeError: Cannot read property 'interval' of null
    at MessagePort.handle_message (https://echo.jefftk.com/app.js:1208:64)
```

On a couple occasions now, I've gotten this immediately after completing volume calibration.

**Comment by jeffkaufman** [comment]
I noticed that this was being caused by something in a LOG_SPAM so I just deleted the spammy a log message.

This did not fix the actual problem, however, and now the bug looks like:

```
TypeError: Cannot read property 'check_clock_reference' of null
TypeError: Cannot read property 'check_clock_reference' of null
    at AudioDecoder.decode_chunk (https://echo.jefftk.com/app.js:693:11)
    at MessagePort.handle_message (https://echo.jefftk.com/app.js:1211:36)
```

I think the problem is `response` doesn't contain a `response_chunk` key?

Is "// XXX: interesting, it does not seem that these promises are guaranteed to resolve in order... and the worklet's buffer uses the first chunk's timestamp to decide where to start playing back, so if the first two chunks are swapped it has a big problem." the issue?
