### ISSUE TITLE
Create APIs to know when bucket brigade is being hampered by CPU and/or bandwidth contention

### ISSUE THREAD

**Issue by taymonbeal** [gwillen/solstice-audio-test#71]
Per Facebook conversation. These can only be heuristics but that might be good enough.

**Comment by gwillen** [comment]
Proposal was something like:

* "networkFailed" event (would always fire alongside "connectivityChange", but would indicate that it was disconnected due to problems and not because we asked it to)
* "audioLag" event (would fire probably instead of the current "your computer is too slow" error message; we could lower the threshold for firing, and we could include some estimate of "how bad" the problem is in the event.)

We could also have a "playBufferUnderflow" event, if we want to capture that -- this indicates that we ran out of audio to play (at least temporarily), which will glitch the user's _local_ audio (but not automatically their outgoing audio, though the two are likely associated.) I usually find that this is associated with either CPU or network problems, but sometimes transient and not bad enough to trigger the bigger issues (network disconnection / the extreme audio lag error.) For awhile our response to this was to throw an exception, similar to the "your computer is too slow" error, but now we "ride through" by simply assuming the issue is transient and playing silence until we catch up. (If the issue is not transient, it's generally followed by a network disconnection, which solves it anyway.)
