### ISSUE TITLE
BucketSinging error in ritualEngine

### ISSUE THREAD

**Issue by taymonbeal** [gwillen/solstice-audio-test#98]
See dspeyer/ritualEngine#113.

**Comment by gwillen** [comment]
Has this been seen again since 5 days ago? Does it get seen often?

I added some more checks in various places to try to nail it down, but so far I haven't heard anybody mention hitting any of them (or mention hitting this again, but I could imagine maybe people are ignoring it or something -- please do let me know if you hit it, this is a "should never happen").

**Comment by jeffkaufman** [comment]
I don't think this is happening anymore
